name: Build Android

on: [push, pull_request]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Cordova
        run: npm install -g cordova@10.0.0

      - name: Install Ionic
        run: npm install -g @ionic/cli@6.17.1

      - name: Install app dependencies
        run: npm install

      - name: Add Android platform
        run: ionic cordova platform add android@latest
        run: ionic cordova prepare android

      - name: Build Android Dev APK
        run: ionic cordova build android --prod --stacktrace