name: "CI"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - workflow

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: 8
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
    - name: Run cordova project
      run: |
        cordova platform rm android && cordova platform add android
        ionic cordova prepare
        ionic cordova build android --stacktrace

